// ACTION TYPES
export const LOAD_SPECOFFER_CHOOSER_START = 'LOAD_SPECOFFER_CHOOSER_START';
export const LOAD_SPECOFFER_CHOOSER_SUCCESS= 'LOAD_SPECOFFER_CHOOSER_SUCCESS';
export const LOAD_SPECOFFER_CHOOSER_FAIL = 'LOAD_SPECOFFER_CHOOSER_FAIL';

export const LOAD_RATING_LIST_START = 'LOAD_RATING_LIST_START';
export const LOAD_RATING_LIST_SUCCESS= 'LOAD_RATING_LIST_SUCCESS';
export const LOAD_RATING_LIST_FAIL = 'LOAD_RATING_LIST_FAIL';

// reducer name
export const RATING = 'rating';