// ACTION TYPES
export const LOAD_SPECOFFER_CHOOSER_START = 'LOAD_SPECOFFER_CHOOSER_START';
export const LOAD_SPECOFFER_CHOOSER_SUCCESS= 'LOAD_SPECOFFER_CHOOSER_SUCCESS';
export const LOAD_SPECOFFER_CHOOSER_FAIL = 'LOAD_SPECOFFER_CHOOSER_FAIL';

// reducer name
export const RATING = 'rating';