// ACTION TYPES
export const LOAD_SPECOFFER_CHOOSER_START = 'LOAD_SPECOFFER_CHOOSER_START';
export const LOAD_SPECOFFER_CHOOSER_SUCCESS= 'LOAD_SPECOFFER_CHOOSER_SUCCESS';
export const LOAD_SPECOFFER_CHOOSER_FAIL = 'LOAD_SPECOFFER_CHOOSER_FAIL';

export const LOAD_RATING_START = 'LOAD_RATING_START';
export const LOAD_RATING_SUCCESS= 'LOAD_RATING_SUCCESS';
export const LOAD_RATING_FAIL = 'LOAD_RATING_FAIL';

export const DEPARTMENT_PICKED = 'DEPARTMENT_PICKED';
export const SPECOFFER_PICKED = 'SPECOFFER_PICKED';

// reducer name
export const RATING = 'rating';