export const LOAD_ALL_ENROLMENTS_START = 'LOAD_ALL_ENROLMENTS_START';
export const LOAD_ALL_ENROLMENTS_SUCCESS= 'LOAD_ALL_ENROLMENTS_SUCCESS';
export const LOAD_ALL_ENROLMENTS_FAIL = 'LOAD_ALL_ENROLMENTS_START';

